### PR TITLE
update ci workflow

### PR DESCRIPTION
**Pull request by kturney**
## Summary
Revamps and fixes CI workflow.

## Updates
- migrated `rust-toolchain` to newer `rust-toolchain.toml`
- utilized the [`rustup` included in `ubuntu-latest`](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) to install the toolchain specified in `rust-toolchain.toml`
- based Rust CI setup on the [`rust-analyzer` CI workflow](https://github.com/rust-lang/rust-analyzer/blob/master/.github/workflows/ci.yaml)
  - added caching
  - added faster build ordering
  - added separation of test build and test execution
  - disabled incremental builds in CI
- used available actions to install additional languages instead of leaning on `apt-get` directly

## Potential shortcomings
- had to use newer Swift than readme says serge-reflection supports (5.7 instead of 5.3) due to [gpg issues with older Swift versions](https://github.com/swift-actions/setup-swift/issues/520)
- had to add an include for `std::numeric_limits` to fix cpp tests, matching fix found [here](https://github.com/potree/PotreeConverter/pull/585). I'm not sure if that is considered a breaking change.

## Misc
[Warnings during tests](https://github.com/zefchain/serde-reflection/actions/runs/3978266779/jobs/6819942885#step:16:240) indicate that .Net@2.1 is no longer supported. We could use this opportunity to bump the minimum support versions of different supported runtimes.

### CODE REVIEW

**Comment by ma2bd** [comment]
@kturney Thanks for the PR. This looks great! My only ask is that we keep using the pinned version of Rust (aka the one from rust-toolchain) in CI. Otherwise, I believe CI may break (typically clippy) whenever `ubuntu-latest` changes.

**Review by ma2bd — CHANGES_REQUESTED** [review]
back to your queue

**Comment by kturney** [comment]
Hi @ma2bd, thanks for the quick review!
Since the `rust-toolchain.toml` is there, CI is currently pinned to using 1.60.0 for everything.
And it's my understanding that will only change if we update the `toolchain` in the `rust-toolchain.toml`.
Is that not correct?

Are you wanting me to change every use of `cargo` to `cargo +1.60.0` to be extra certain?

**Review by ma2bd — APPROVED** [review]
Oh I see. It looks like that `rustup show` actually installs the missing toolchain so we're good!

**Pull request merged**
